-- Run this in your Supabase SQL Editor to add the missing columns

-- Add missing columns to vehicles table
ALTER TABLE vehicles 
ADD COLUMN IF NOT EXISTS insurance_expiry DATE,
ADD COLUMN IF NOT EXISTS maintenance_km INTEGER DEFAULT 50000,
ADD COLUMN IF NOT EXISTS kilometers_driven INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS vehicle_status TEXT DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Add missing columns to drivers table
ALTER TABLE drivers
ADD COLUMN IF NOT EXISTS age INTEGER,
ADD COLUMN IF NOT EXISTS license_number TEXT,
ADD COLUMN IF NOT EXISTS license_expiry DATE,
ADD COLUMN IF NOT EXISTS ratings NUMERIC DEFAULT 5.0,
ADD COLUMN IF NOT EXISTS pin_hash TEXT DEFAULT '1234',
ADD COLUMN IF NOT EXISTS assigned_vehicle UUID REFERENCES vehicles(id),
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS total_trips INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS on_time_percentage NUMERIC DEFAULT 100.0,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
